language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t niksadi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true niksadi/react-test npm test
after_success:
  - docker build -t niksadi/multi-client ./client
  - docker build -t niksadi/multi-nginx ./nginx
  - docker build -t niksadi/multi-server ./server
  - docker build -t niksadi/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push  niksadi/multi-client
  - docker push  niksadi/multi-nginx
  - docker push  niksadi/multi-server
  - docker push  niksadi/multi-worker 
deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-111556527257
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY